name: Maven builder

on:
  push:
    branches: [ "master", "feature/*", "bugfix/*", "hotfix/*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build soodoku-core with Maven
        run: mvn -B package --file soodoku-core/pom.xml
